import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import ApolloProvider from './providers';

import './globals.css';
import { ThemeContextProvider } from '@/components/context/ThemeContextProvider/ThemeContextProvider';
import { Header } from '@/components/Header/Header';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-white`}
            >
                <ThemeContextProvider>
                    <Header />
                    <ApolloProvider>{children}</ApolloProvider>
                </ThemeContextProvider>
            </body>
        </html>
    );
}
